name: comman_templates
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_add_to_cart_button: ^1.0.0+1
  flutter_login: ^2.2.1
  easy_onboarding: ^1.0.0
  flutter_easyloading: ^3.0.0
  flutter_easyrefresh: ^2.2.1
  http: ^0.13.3
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  google_sign_in: ^5.0.7
  ms_undraw: ^3.0.0+0
  sizer: ^2.0.13
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
